sentences = [
    "Quero investir R$ 7 500,00 em PETR4 amanhã.",
    "Pretendo aplicar dez mil reais no fundo HGLG11 este mês.",
    "Vou colocar 3 000 reais na ação VALE3 assim que possível.",
    "Planejo aportar R$ 2.500 no ETF BOVA11 na terça-feira.",
    "Desejo investir 5 mil em ITUB4 para longo prazo.",
    "Reservarei R$ 12 000 para comprar cotas de KNRI11.",
    "Quero aplicar quinhentos reais em BBAS3 ainda hoje.",
    "Penso em destinar R$ 15 mil ao fundo XPLG11 mês que vem.",
    "Vou investir 2 000,00 reais na ação BBDC4.",
    "Planejo colocar R$ 9 800 em FII VISC11.",
    "Decidi investir vinte mil reais em LFT 2029 do Tesouro.",
    "Pretendo aportar R$ 1 200 no ETF SMALL11.",
    "Quero investir R$ 30 000,00 na cripto BTC via ETF.",
    "Reservarei mil e quinhentos reais para ABEV3.",
    "Vou aplicar R$ 4 300 em cotas do FII HGRE11.",
    "Penso em investir R$ 18 mil na PETZ3.",
    "Destinarei 2 500 reais ao fundo MXRF11.",
    "Quero aplicar R$ 6 750 em EGIE3 ainda esta semana.",
    "Pretendo aportar 4 000,00 no FII BRCR11.",
    "Planejo investir R$ 22 000 em BRKM5.",
    "Vou destinar oito mil reais para cotas de HCTR11.",
    "Estou pensando em investir R$ 11 000,00 em ETF IVVB11.",
    "Desejo colocar 3 400 reais em SUZB3.",
    "Quero aplicar R$ 27 500 no FII HGBS11.",
    "Pretendo investir R$ 800,00 em MGLU3 nesta sexta.",
    "Vou reservar quinze mil reais para Tesouro Selic 2028.",
    "Planejo aportar R$ 5 600 em FII RBRF11.",
    "Quero investir R$ 13 750,00 na ação CSNA3.",
    "Penso em aplicar dois mil reais em SEER3.",
    "Vou colocar R$ 40 000 no ETF HASH11 de cripto.",
    "Desejo investir R$ 2 200 na PETR4 novamente.",
    "Reservarei 6 000 reais para comprar ODPV3.",
    "Pretendo aplicar R$ 9 250 no FII VGIR11.",
    "Quero aportar R$ 1 050 em ETF SMAL11 este trimestre.",
    "Planejo investir sete mil e quinhentos reais em FII ALZR11.",
    "Decidi destinar R$ 14 000,00 para RAIL3.",
    "Vou investir R$ 19 500 em cotas do HGRU11.",
    "Penso em colocar 1 800 reais em WEGE3.",
    "Pretendo aplicar R$ 25 000 no ETF BDRX11.",
    "Quero investir três mil reais em TASA4.",
    "Planejo aportar R$ 10 600 no FII HGCR11.",
    "Vou destinar R$ 8 900 para AÇÃO PRIO3.",
    "Desejo aplicar 6 400 reais no ETF GOLD11.",
    "Pretendo investir R$ 17 300,00 em AMBIPAR3.",
    "Quero colocar doze mil reais em FII VILG11.",
    "Penso em investir R$ 21 000 em BRFS3.",
    "Vou aplicar R$ 950,00 na ação CIEL3.",
    "Planejo destinar 4 700 reais ao ETF FIND11.",
    "Desejo investir R$ 28 000 no FII HFOF11.",
    "Pretendo aportar R$ 3 300 em JHSF3 antes do fim do mês."
]